### ISSUE TITLE
Fails to build on arm/darwin due to duplicate symbols

### ISSUE THREAD

**Issue by 8tt** [cznic/fileutil#14]
Error when building with gomobile:

gomobile: go install -pkgdir=/Users/a/repos/tt-ios/go/pkg/gomobile/pkg_darwin_arm -tags="" ll/ttgo/ttgo failed: exit status 2 # ll/ttgo/ttgo/vendor/github.com/cznic/fileutil go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_darwin.go:14: PunchHole redeclared in this block     previous declaration at go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_arm.go:14 go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_darwin.go:20: Fadvise redeclared in this block  previous declaration at go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_arm.go:20 go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_darwin.go:25: IsEOF redeclared in this block    previous declaration at go/src/ll/ttgo/ttgo/vendor/github.com/cznic/fileutil/fileutil_arm.go:25

**Comment by cznic** [comment]
Thanks for the patch. Can you please make it a PR, in which you would also add yourself to the AUTHORS and/or CONTRIBUTORS?
